# Generated by Django 5.2.5 on 2025-09-07 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_location_alter_asset_owner'),
        ('owners', '0002_remove_owner_department_alter_owner_location'),
        ('ownership_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershiphistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_history', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='from_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='owners.owner'),
        ),
        migrations.AlterField(
            model_name='ownershiphistory',
            name='to_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='owners.owner'),
        ),
    ]
