# Generated by Django 5.2.5 on 2025-09-07 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_department'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='department',
        ),
        migrations.AlterField(
            model_name='owner',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='locations.location'),
        ),
    ]
